{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "shark-android",
    "version": "2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "shark-android-2.10.jar",
          "url": "shark-android-2.10.jar",
          "size": 369144,
          "sha512": "1462f65fe2f878d75415f21884c731bab56298a87479d9ec30bcede0c45c7c226782da162ca235969a22897df736f7aaeb841354a5c5f87ba411e56e3e4431ba",
          "sha256": "c1a28d92f667b80da6aa6ce0196fd15ba6f9d7899ac44cc450193a06c9a76b61",
          "sha1": "919cd08c15dbaff469a1837f1efa22a5b16232cc",
          "md5": "f18cf60d6182b21215a6478b90a8896a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "shark-android-2.10.jar",
          "url": "shark-android-2.10.jar",
          "size": 369144,
          "sha512": "1462f65fe2f878d75415f21884c731bab56298a87479d9ec30bcede0c45c7c226782da162ca235969a22897df736f7aaeb841354a5c5f87ba411e56e3e4431ba",
          "sha256": "c1a28d92f667b80da6aa6ce0196fd15ba6f9d7899ac44cc450193a06c9a76b61",
          "sha1": "919cd08c15dbaff469a1837f1efa22a5b16232cc",
          "md5": "f18cf60d6182b21215a6478b90a8896a"
        }
      ]
    }
  ]
}
