{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-1.3.1.aar",
          "url": "ui-tooling-1.3.1.aar",
          "size": 137051,
          "sha512": "17a48b492eaac7406bbbe3f9b57160214cab9de3d14903cc2dcc3eae5a02083898e2325869086765df4fcb00f42fa943f370aede275a9ae637455f403130af7a",
          "sha256": "ff155931340e97653ce6c504e1bdb375c5c8e997fbcc3e5b55b34c8b062b4281",
          "sha1": "5de7f614411781131ce3657f2c057398476305c0",
          "md5": "717d1ae2ea3aaa5c722604e0554d9824"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-1.3.1.aar",
          "url": "ui-tooling-1.3.1.aar",
          "size": 137051,
          "sha512": "17a48b492eaac7406bbbe3f9b57160214cab9de3d14903cc2dcc3eae5a02083898e2325869086765df4fcb00f42fa943f370aede275a9ae637455f403130af7a",
          "sha256": "ff155931340e97653ce6c504e1bdb375c5c8e997fbcc3e5b55b34c8b062b4281",
          "sha1": "5de7f614411781131ce3657f2c057398476305c0",
          "md5": "717d1ae2ea3aaa5c722604e0554d9824"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-1.3.1-sources.jar",
          "url": "ui-tooling-1.3.1-sources.jar",
          "size": 25427,
          "sha512": "c1aabd82a4c14c3f914a3239e36b94a9f3181fdac48b27d15797eacf6e8d64b8f67c4154cf034a481f9c689de94c12b57bbee2ff5dbe87a8d69c269f7db2a925",
          "sha256": "b3a2c7622d447ef8624c82f8f63e9e6318eb9ff8ed2a89ead95cbab32111b447",
          "sha1": "d08e3e4494771af1ea96585233d891d9ba5d0338",
          "md5": "c0036b421540605775f7628ef4dfef8b"
        }
      ]
    }
  ]
}