{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget",
    "version": "1.0.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.0.0-alpha05.aar",
          "url": "glance-appwidget-1.0.0-alpha05.aar",
          "size": 1835960,
          "sha512": "fdcf243b84fdd20457ce15baad3dc41f83f9517902eb357cbfc8fa41e3303c83da26ed5b4e3fdbb57a91e1a99130c822218649ffae8445c858139db7993d55e5",
          "sha256": "88ab6ff6e1ab050d82b0cfbb8b97b633096ee84ad8c0649d5a337c6c220380bd",
          "sha1": "7bcc2947d2c77e77a8c330464bcc5fd9c2277234",
          "md5": "b6b3286da028d506a740ca190211cfa8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-remoteviews",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.0.0-alpha05.aar",
          "url": "glance-appwidget-1.0.0-alpha05.aar",
          "size": 1835960,
          "sha512": "fdcf243b84fdd20457ce15baad3dc41f83f9517902eb357cbfc8fa41e3303c83da26ed5b4e3fdbb57a91e1a99130c822218649ffae8445c858139db7993d55e5",
          "sha256": "88ab6ff6e1ab050d82b0cfbb8b97b633096ee84ad8c0649d5a337c6c220380bd",
          "sha1": "7bcc2947d2c77e77a8c330464bcc5fd9c2277234",
          "md5": "b6b3286da028d506a740ca190211cfa8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "glance-appwidget-1.0.0-alpha05-sources.jar",
          "url": "glance-appwidget-1.0.0-alpha05-sources.jar",
          "size": 102563,
          "sha512": "ad53e02a395d1baa2d0623588d22b54d914cf856f0a4a662403edfc9b9366d12f33c93247a818ebf0a98fe96ebfb3ebf30fca3a3c0ea9c9aedb022f011ef7acb",
          "sha256": "41aae4b420308f7d8db97bc47a2ae279f3d6a291dbef68ceb2490c372bded1c6",
          "sha1": "c50d12941d583b1d8e72e773a0883733864f50a0",
          "md5": "fba1de3c1a5b729c65ff0f63cef92e45"
        }
      ]
    }
  ]
}