{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "shark-hprof",
    "version": "2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "shark-hprof-2.10.jar",
          "url": "shark-hprof-2.10.jar",
          "size": 154807,
          "sha512": "2b622934e38dd59ea8f1447873b9c578bf8ba182322d827d4bdbd61fe1d81faa03fe9280cd727a94e8dd76b27dbdf5e37646bc2b47f0695a0fe161ef513aa52d",
          "sha256": "7befebc19b69d62b61e66c6a853742ea6fed251ebaed84ff4d57fcbd78e9e1cc",
          "sha1": "d0c58306d9dc3c8caf44256ddee29918c524bd1a",
          "md5": "c7f11279680e0abffef85d0c8d0c0138"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "shark-hprof-2.10.jar",
          "url": "shark-hprof-2.10.jar",
          "size": 154807,
          "sha512": "2b622934e38dd59ea8f1447873b9c578bf8ba182322d827d4bdbd61fe1d81faa03fe9280cd727a94e8dd76b27dbdf5e37646bc2b47f0695a0fe161ef513aa52d",
          "sha256": "7befebc19b69d62b61e66c6a853742ea6fed251ebaed84ff4d57fcbd78e9e1cc",
          "sha1": "d0c58306d9dc3c8caf44256ddee29918c524bd1a",
          "md5": "c7f11279680e0abffef85d0c8d0c0138"
        }
      ]
    }
  ]
}
