{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.3.1.aar",
          "url": "animation-core-1.3.1.aar",
          "size": 1337763,
          "sha512": "709de28454a9225e8d4756fef6c4387b1622f426dc42ebe98ea030ff739d883ee65b6108d5142a4c175007fd25bb46ccca4f6f4b62ab053d9da53e9f2eff5330",
          "sha256": "430bd0fb29a10b707abdf5750f4a28826ecf455838950c1cb86ce67ba91c6e16",
          "sha1": "3c7ce80fa9146bd7bd626af56187d0384c765f24",
          "md5": "1fd675925272a30dd074e404429b021a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.3.1.aar",
          "url": "animation-core-1.3.1.aar",
          "size": 1337763,
          "sha512": "709de28454a9225e8d4756fef6c4387b1622f426dc42ebe98ea030ff739d883ee65b6108d5142a4c175007fd25bb46ccca4f6f4b62ab053d9da53e9f2eff5330",
          "sha256": "430bd0fb29a10b707abdf5750f4a28826ecf455838950c1cb86ce67ba91c6e16",
          "sha1": "3c7ce80fa9146bd7bd626af56187d0384c765f24",
          "md5": "1fd675925272a30dd074e404429b021a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-1.3.1-sources.jar",
          "url": "animation-core-1.3.1-sources.jar",
          "size": 76120,
          "sha512": "632efcf8fd10b3f72063e3e2004a1e3ec739fddaf2dc2db05563046890423cf76ce23a0e6bbb98ae3cbba4550b6beedb6bf52bae87b1b16d6f5ec030bcd258e3",
          "sha256": "ead476a0e7882485fa92eae41fcd53dcc913971f6890511e0c1c7945c93eb8e4",
          "sha1": "90652b3f4ec58da8d29d8c1518f1b60068b9d28c",
          "md5": "2170b5f80666aafb56ff92497c62a50b"
        }
      ]
    }
  ]
}