{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-manifest",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.3.1.aar",
          "url": "ui-test-manifest-1.3.1.aar",
          "size": 9142,
          "sha512": "7b8e0c5258cfef3f03e9188c20ab570571434f895044014f1c13fd2e1257df6b171a54ef1ae3026171eeb164292b3cfe776d68bf2d268fc5daba396269c7f1e1",
          "sha256": "b00bf6cb68bd52e78f191450fbb3e7ce4f744f0eed204a415640a93bf501f2ef",
          "sha1": "1b8b9cd3d429c476919fecd672422f9d1cd40eed",
          "md5": "50d3251ec08ccb6e706a58127816c3f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.3.1.aar",
          "url": "ui-test-manifest-1.3.1.aar",
          "size": 9142,
          "sha512": "7b8e0c5258cfef3f03e9188c20ab570571434f895044014f1c13fd2e1257df6b171a54ef1ae3026171eeb164292b3cfe776d68bf2d268fc5daba396269c7f1e1",
          "sha256": "b00bf6cb68bd52e78f191450fbb3e7ce4f744f0eed204a415640a93bf501f2ef",
          "sha1": "1b8b9cd3d429c476919fecd672422f9d1cd40eed",
          "md5": "50d3251ec08ccb6e706a58127816c3f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-manifest-1.3.1-sources.jar",
          "url": "ui-test-manifest-1.3.1-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}