{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling-data",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-data-1.3.1.aar",
          "url": "ui-tooling-data-1.3.1.aar",
          "size": 37600,
          "sha512": "77c577ab6220ffd9bfc7605778ef2e4671b49b33f967d51ca14f8b08c2e2cda3c3732520ace9c5d411d9df2afeb55c158197a7e835cfe5094cdeb3db76fbb84a",
          "sha256": "6eef09a9caf1349b01655bd58799632de3d8730b2117f974a86a38e2b67f7b7d",
          "sha1": "437fe7bbc4c8b8e6deecc2be42fa731b7515f811",
          "md5": "831c1858ea5d8b5c8b162ded28b362ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-data-1.3.1.aar",
          "url": "ui-tooling-data-1.3.1.aar",
          "size": 37600,
          "sha512": "77c577ab6220ffd9bfc7605778ef2e4671b49b33f967d51ca14f8b08c2e2cda3c3732520ace9c5d411d9df2afeb55c158197a7e835cfe5094cdeb3db76fbb84a",
          "sha256": "6eef09a9caf1349b01655bd58799632de3d8730b2117f974a86a38e2b67f7b7d",
          "sha1": "437fe7bbc4c8b8e6deecc2be42fa731b7515f811",
          "md5": "831c1858ea5d8b5c8b162ded28b362ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-data-1.3.1-sources.jar",
          "url": "ui-tooling-data-1.3.1-sources.jar",
          "size": 8644,
          "sha512": "76228f07045b120816c98d6774a2a45709a6194d36a51995ee3c82c1548e68718b7acc9bef73f3b6d401cf7f3ff6ed95378643a55670f206a81e803ede58606d",
          "sha256": "904d95e98fada3f45f809e1c0966cee967b3d05e6cb8b07011621fb2db3cefdb",
          "sha1": "0dcb5766eb670128ddbafbd04fe3fc9fab8fbb7e",
          "md5": "fcf744a8402b33885168247aec4000b0"
        }
      ]
    }
  ]
}