{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-object-watcher-android-androidx",
    "version": "2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-core",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-android-androidx-2.10.aar",
          "url": "leakcanary-object-watcher-android-androidx-2.10.aar",
          "size": 9521,
          "sha512": "ec95e2bddab8f98b7be821409be31aed9ed332684e0a798574adc9214f2c72cad16a78a4b67950b75ab4e08a4d26763780e1c1b9eea049c619aa2d886a13558f",
          "sha256": "80845812373c5ddf0909e2cbcaf58d757d2253cd8e258ec152d29286177c7539",
          "sha1": "5bb24ed2c490bd9f69c350666c7b4ac1cb7505b4",
          "md5": "993e436699b4584540ecfb425f4d221d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-core",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-android-androidx-2.10.aar",
          "url": "leakcanary-object-watcher-android-androidx-2.10.aar",
          "size": 9521,
          "sha512": "ec95e2bddab8f98b7be821409be31aed9ed332684e0a798574adc9214f2c72cad16a78a4b67950b75ab4e08a4d26763780e1c1b9eea049c619aa2d886a13558f",
          "sha256": "80845812373c5ddf0909e2cbcaf58d757d2253cd8e258ec152d29286177c7539",
          "sha1": "5bb24ed2c490bd9f69c350666c7b4ac1cb7505b4",
          "md5": "993e436699b4584540ecfb425f4d221d"
        }
      ]
    }
  ]
}
