{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "shark",
    "version": "2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-graph",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "shark-2.10.jar",
          "url": "shark-2.10.jar",
          "size": 345548,
          "sha512": "980321ebc77b05d4b6aa4ea42a7ad043e727469c8fdc0754a3118a69547f9518c44fd13361c3a9bd8d2891947aa74afc9034f7ae2c50ea73f350e939216e0c57",
          "sha256": "3084e4cdd0c0770bf3dfbf264ef5874c5cd8a661ace218f5cd9cc90d24627bd5",
          "sha1": "e92cb86c514562f1f591622c47c51f3f2a7d2489",
          "md5": "16e617d64b8074f1c77272c9069449fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-graph",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "shark-2.10.jar",
          "url": "shark-2.10.jar",
          "size": 345548,
          "sha512": "980321ebc77b05d4b6aa4ea42a7ad043e727469c8fdc0754a3118a69547f9518c44fd13361c3a9bd8d2891947aa74afc9034f7ae2c50ea73f350e939216e0c57",
          "sha256": "3084e4cdd0c0770bf3dfbf264ef5874c5cd8a661ace218f5cd9cc90d24627bd5",
          "sha1": "e92cb86c514562f1f591622c47c51f3f2a7d2489",
          "md5": "16e617d64b8074f1c77272c9069449fe"
        }
      ]
    }
  ]
}
