{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-remoteviews",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteviews-1.0.0-beta03.aar",
          "url": "core-remoteviews-1.0.0-beta03.aar",
          "size": 55301,
          "sha512": "5b883d69be38cbcc17e5fa9c0521158eaa079ce3615ecd76e103ea29e2271de04018141a33958846876927903b68ab76903a445fc2fbe85a55294a995315dafe",
          "sha256": "a9f86357aa686d520ffe9a7f3fa0cacd8410e4912fbc767f217b3e2abe39c9e1",
          "sha1": "d61629faa90fd5c0f9b468d604d2779da0f6a66f",
          "md5": "e4a1e5826a0479279fc43743d49dab8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteviews-1.0.0-beta03.aar",
          "url": "core-remoteviews-1.0.0-beta03.aar",
          "size": 55301,
          "sha512": "5b883d69be38cbcc17e5fa9c0521158eaa079ce3615ecd76e103ea29e2271de04018141a33958846876927903b68ab76903a445fc2fbe85a55294a995315dafe",
          "sha256": "a9f86357aa686d520ffe9a7f3fa0cacd8410e4912fbc767f217b3e2abe39c9e1",
          "sha1": "d61629faa90fd5c0f9b468d604d2779da0f6a66f",
          "md5": "e4a1e5826a0479279fc43743d49dab8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-remoteviews-1.0.0-beta03-sources.jar",
          "url": "core-remoteviews-1.0.0-beta03-sources.jar",
          "size": 20472,
          "sha512": "3e57f0cadf9bca09431c20e590a2ca70a0f72c802dee2c9eed4be341ffde849cc375aaef7e6fbed9171563a038643a4f09c866eacee065aa86ac4f8c7d9a7c28",
          "sha256": "a91b520278f182454311fdf978af9aa4a812a98add9803cc3f53f1b068611bee",
          "sha1": "7a6e8a0a697eca82061aeb5d25c75b8d8f110764",
          "md5": "d39504e862b214d1c4310b1e39e8205f"
        }
      ]
    }
  ]
}