{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-object-watcher",
    "version": "2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-2.10.jar",
          "url": "leakcanary-object-watcher-2.10.jar",
          "size": 16911,
          "sha512": "317939a06b3bc2b9b82af4c207e4644abc9f28b1bc65f6099a064176f80102276193621668b8444f4c97f2b2a921b382d916775566a8d076e00bdcd0c89a125e",
          "sha256": "bf291e626a953dfb79b2b97ac766d664c7e1ad3856aef2fb84db7d99d7602b3d",
          "sha1": "5d91af6785d9d15f51cd08f7c5e52874b2ddea3f",
          "md5": "3f6091fd154fa7a044d5d95cd4f90e13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-2.10.jar",
          "url": "leakcanary-object-watcher-2.10.jar",
          "size": 16911,
          "sha512": "317939a06b3bc2b9b82af4c207e4644abc9f28b1bc65f6099a064176f80102276193621668b8444f4c97f2b2a921b382d916775566a8d076e00bdcd0c89a125e",
          "sha256": "bf291e626a953dfb79b2b97ac766d664c7e1ad3856aef2fb84db7d99d7602b3d",
          "sha1": "5d91af6785d9d15f51cd08f7c5e52874b2ddea3f",
          "md5": "3f6091fd154fa7a044d5d95cd4f90e13"
        }
      ]
    }
  ]
}
