{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.3.1.aar",
          "url": "ui-tooling-preview-1.3.1.aar",
          "size": 13168,
          "sha512": "e834246d52cb0caa1080ac40773d978072e7f9b01ba935b978129dc0a1a8d81d5557c247cc392ca08ea230bf21978b3a3bd17131e6f3c630d4505b6e488d1237",
          "sha256": "917299b91b2fb136394ab3c0a0fc1a2c0645bd074dbb57a5ea92869c0c25edac",
          "sha1": "ebb32779edaa84b99bc1908a04e37eda0bcf58a3",
          "md5": "7e7455c61679a85248a70c9eedc9bd18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-1.3.1.aar",
          "url": "ui-tooling-preview-1.3.1.aar",
          "size": 13168,
          "sha512": "e834246d52cb0caa1080ac40773d978072e7f9b01ba935b978129dc0a1a8d81d5557c247cc392ca08ea230bf21978b3a3bd17131e6f3c630d4505b6e488d1237",
          "sha256": "917299b91b2fb136394ab3c0a0fc1a2c0645bd074dbb57a5ea92869c0c25edac",
          "sha1": "ebb32779edaa84b99bc1908a04e37eda0bcf58a3",
          "md5": "7e7455c61679a85248a70c9eedc9bd18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-preview-1.3.1-sources.jar",
          "url": "ui-tooling-preview-1.3.1-sources.jar",
          "size": 8239,
          "sha512": "2795ac4812692f0bb675e4060213fc3a89034fdb2c6e1550b82f1971b808d432fdda4c824498ca2ce2d325b82afbe635b3466e3c5d6a5a408f0c48626eaa98e2",
          "sha256": "a651ab0ce34d8f89f8f34b969ea26c82c8ce43bc00c79415fa790e3d5ef899f1",
          "sha1": "8432308a1cb0e2db5ff0f8ff31398f5293b22573",
          "md5": "6ab2ee3958d14aaa72cdc53fec530d03"
        }
      ]
    }
  ]
}