{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-extended",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-1.3.1.aar",
          "url": "material-icons-extended-1.3.1.aar",
          "size": 32356763,
          "sha512": "7a5a56fea8a0b643fa505a6ca2341d005d227f235ab98a2bd8d4134ad81711258ffb2ec8154dea7c2a149d61801715200f4cc774ecfe8de3cf41a9d99c260550",
          "sha256": "b70f1c72811de58ccc33ad1f7248ddc93c407b8248bf176eb0c9737509f59487",
          "sha1": "f1d3d21294fe4ed9b7e63b97337a58c020f61b42",
          "md5": "b4b27b5e860f00862ba688422faa7250"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-1.3.1.aar",
          "url": "material-icons-extended-1.3.1.aar",
          "size": 32356763,
          "sha512": "7a5a56fea8a0b643fa505a6ca2341d005d227f235ab98a2bd8d4134ad81711258ffb2ec8154dea7c2a149d61801715200f4cc774ecfe8de3cf41a9d99c260550",
          "sha256": "b70f1c72811de58ccc33ad1f7248ddc93c407b8248bf176eb0c9737509f59487",
          "sha1": "f1d3d21294fe4ed9b7e63b97337a58c020f61b42",
          "md5": "b4b27b5e860f00862ba688422faa7250"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-extended-1.3.1-sources.jar",
          "url": "material-icons-extended-1.3.1-sources.jar",
          "size": 11067229,
          "sha512": "96bf38e9e36d6e4711353256fbd476dd1cf31e788fc7682254ae975ec131f42e9126e2caed038bb4fb3262a6d02075303eaa9579d4d45e9c104f4d30204e6b19",
          "sha256": "01967bebfd54970d5d3eb678852400b652f90a30da8e439c668c7fdcf6b58991",
          "sha1": "f7f634aaf9e00d11c1f8ec3c7e3a364ee67d6f69",
          "md5": "c316a614924d452c10251659a10ad264"
        }
      ]
    }
  ]
}