{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.3.1.aar",
          "url": "animation-1.3.1.aar",
          "size": 1298390,
          "sha512": "735b6592647fa67edbbe40fc7d7d25b6801e922e563e387bfdf94bf979c1e439878ef3a6c024572608b73a51fcd87ed923183e2c2adcc90b66f674a9c9a3332a",
          "sha256": "2c37dcd22d18fa7934410d211ee65409ec90ba0a61dfd56eeb6fa6f69e7fecff",
          "sha1": "5aeb04800becc2e65b8e8480e089c041f2960e3e",
          "md5": "84bab4bac78705965caf10a182cb2656"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.3.1.aar",
          "url": "animation-1.3.1.aar",
          "size": 1298390,
          "sha512": "735b6592647fa67edbbe40fc7d7d25b6801e922e563e387bfdf94bf979c1e439878ef3a6c024572608b73a51fcd87ed923183e2c2adcc90b66f674a9c9a3332a",
          "sha256": "2c37dcd22d18fa7934410d211ee65409ec90ba0a61dfd56eeb6fa6f69e7fecff",
          "sha1": "5aeb04800becc2e65b8e8480e089c041f2960e3e",
          "md5": "84bab4bac78705965caf10a182cb2656"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-1.3.1-sources.jar",
          "url": "animation-1.3.1-sources.jar",
          "size": 41549,
          "sha512": "0253c53023634ec3d103195919fdc20cd4c3523b019deabbb7b272e2208b44b425f55edf8cfef3d536b193da110d327d7b487f53528fa4187a45a1dcc9065986",
          "sha256": "f5e038bcdf533c9278894be4616ca78b37e36bd58a09775fdf213bd905a90f8d",
          "sha1": "d64ade845a81f037d58035f96aa3f16b7cb5415e",
          "md5": "5b45857888a37084531d6b3278b97c5e"
        }
      ]
    }
  ]
}