{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-junit4",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-1.3.1.aar",
          "url": "ui-test-junit4-1.3.1.aar",
          "size": 146110,
          "sha512": "1ff7377a4477c4811b320417154a53ddcf1eb5b689a49a1f8701ebd14225e7c4e9735f7d76f2b26acaf6345b9c0523d7f08343d0cecd51f3f649cff34487038b",
          "sha256": "fd3798b1f5896a3f53e43aac6c5d9a7dbe5f30d0dd98b4efb008dc8dd6653d3f",
          "sha1": "e118829d5a4de0a72cddd852c93dc7970ec9bf14",
          "md5": "4d963b502f7d22c434b51c0b3c3335d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-idling-resource",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-1.3.1.aar",
          "url": "ui-test-junit4-1.3.1.aar",
          "size": 146110,
          "sha512": "1ff7377a4477c4811b320417154a53ddcf1eb5b689a49a1f8701ebd14225e7c4e9735f7d76f2b26acaf6345b9c0523d7f08343d0cecd51f3f649cff34487038b",
          "sha256": "fd3798b1f5896a3f53e43aac6c5d9a7dbe5f30d0dd98b4efb008dc8dd6653d3f",
          "sha1": "e118829d5a4de0a72cddd852c93dc7970ec9bf14",
          "md5": "4d963b502f7d22c434b51c0b3c3335d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-junit4-1.3.1-sources.jar",
          "url": "ui-test-junit4-1.3.1-sources.jar",
          "size": 41408,
          "sha512": "89d6118e3bae33cbfb3f6b2b3d74c0fcbdfff10b856874ab3f3a71508ef2ce1f51abbed5e21b7d0b1d5b9d2ad8045c417f877d2b81689e4d344331605873a070",
          "sha256": "b64d32c6b8f4b09e56720ff4e3708c1d7be8cf9883a2745703c986fea307a71c",
          "sha1": "a7d4eb63da474ef4481e7d0e4bb5020136e2f3eb",
          "md5": "659361321ad3a459efd849a56ac9dba7"
        }
      ]
    }
  ]
}