{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-android-core",
    "version": "2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-android",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-core",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-androidx",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-support-fragments",
          "version": {
            "requires": "2.10"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-android-core-2.10.aar",
          "url": "leakcanary-android-core-2.10.aar",
          "size": 636022,
          "sha512": "5640a424d9bb92af6742a6677a891301c1f50d95591257c44dd4f6c1e2ed5be759fe7b49e4ebf09eaccbfef36dde8d354ca6318a70b3e64451d24bc38410053f",
          "sha256": "d1f1744f9f8b0b32c1125341d63c1e6d1cfae3c0bf8930d4c7a09690370c8b35",
          "sha1": "9554574e44fda4b68884dc70178d638e29f4fa10",
          "md5": "1954f1305c7a55bd5400892c7b1e8c2e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-android",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-core",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-androidx",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-support-fragments",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-android-core-2.10.aar",
          "url": "leakcanary-android-core-2.10.aar",
          "size": 636022,
          "sha512": "5640a424d9bb92af6742a6677a891301c1f50d95591257c44dd4f6c1e2ed5be759fe7b49e4ebf09eaccbfef36dde8d354ca6318a70b3e64451d24bc38410053f",
          "sha256": "d1f1744f9f8b0b32c1125341d63c1e6d1cfae3c0bf8930d4c7a09690370c8b35",
          "sha1": "9554574e44fda4b68884dc70178d638e29f4fa10",
          "md5": "1954f1305c7a55bd5400892c7b1e8c2e"
        }
      ]
    }
  ]
}
