{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance",
    "version": "1.0.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "glance-1.0.0-alpha05.aar",
          "url": "glance-1.0.0-alpha05.aar",
          "size": 238531,
          "sha512": "4dc50e7b6458f392e049fc38d62c612b4049ddf842886b977bc836d12c65b65afaedbdf469c71cfe7f7747a8e788002ab72103344520df4870fe0a890cf049dc",
          "sha256": "d3fbf1e02d64ef717bdd14b3dd96b1b747a318fe64b773aee4cae4f7359d8ed4",
          "sha1": "47c50c053a42dc6b49f4d5362c9bb1d6b224db22",
          "md5": "a8ecd6aea61cc97a4259c6bf69da7b3d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "glance-1.0.0-alpha05.aar",
          "url": "glance-1.0.0-alpha05.aar",
          "size": 238531,
          "sha512": "4dc50e7b6458f392e049fc38d62c612b4049ddf842886b977bc836d12c65b65afaedbdf469c71cfe7f7747a8e788002ab72103344520df4870fe0a890cf049dc",
          "sha256": "d3fbf1e02d64ef717bdd14b3dd96b1b747a318fe64b773aee4cae4f7359d8ed4",
          "sha1": "47c50c053a42dc6b49f4d5362c9bb1d6b224db22",
          "md5": "a8ecd6aea61cc97a4259c6bf69da7b3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "glance-1.0.0-alpha05-sources.jar",
          "url": "glance-1.0.0-alpha05-sources.jar",
          "size": 51470,
          "sha512": "34b17feab5083f75b74b0d80b67bd62f970cb885aeef2b2f5607a149771f067ccabc091ebfa7de1c5f9185588003bb16d668acf45ce5fcf427a200d4a23b45fc",
          "sha256": "1826005190381cd8ee9eaa8126f3061f485a051d98a86804ec4775dae7f5e7e9",
          "sha1": "df15a218fe1fabd8be8cece791ad4c703aaf7555",
          "md5": "81d2a22d0261ac799786d375a1664d5f"
        }
      ]
    }
  ]
}